@startuml
!include ./style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

mainframe: **sd** Commit addressbook

participant "ac:AddAssignmentCommand" as AddAssignmentCommand LOGIC_COLOR

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

activate AddAssignmentCommand
AddAssignmentCommand -> Model : commitAddressBook(addAssignmentCommandResult)
activate Model

Model --> AddAssignmentCommand
deactivate Model

@enduml
