@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

mainframe: **sd** Mark person at specified week

participant "mc:MarkParticipationCommand" as MarkParticipationCommand LOGIC_COLOR

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

activate MarkParticipationCommand

MarkParticipationCommand -> Model : getFilteredPersonList()
activate Model

Model -> MarkParticipationCommand : lastShownList
deactivate Model

MarkParticipationCommand -> MarkParticipationCommand : createMarkedPerson(personToMark, newParticipationScores)
activate MarkParticipationCommand
MarkParticipationCommand -> MarkParticipationCommand : updatedPerson
deactivate MarkParticipationCommand

MarkParticipationCommand -> Model : setPerson(personToMark, updatedPerson)
activate Model

Model -> MarkParticipationCommand
deactivate Model

MarkParticipationCommand -> Model : updatedFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model

Model -> MarkParticipationCommand
deactivate Model

@enduml
