@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

mainframe: **sd** Create successful CommandResult

participant "mc:MarkParticipationCommand" as MarkParticipationCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR

activate MarkParticipationCommand

create CommandResult
MarkParticipationCommand -> CommandResult : CommandResult(MESSAGE_MARK_PERSON_SUCCESS)
activate CommandResult

CommandResult -> MarkParticipationCommand : r
deactivate CommandResult

@enduml
