@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

mainframe: **sd** Commit addressbook

participant "mc:MarkParticipationCommand" as MarkParticipationCommand LOGIC_COLOR

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

activate MarkParticipationCommand
MarkParticipationCommand -> Model : commitAddressBook(markParticipationCommandResult)
activate Model

Model -> MarkParticipationCommand
deactivate Model

@enduml
