@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

mainframe: **sd** Mark person at specified week

participant "mc:MarkCommand" as MarkCommand LOGIC_COLOR

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

activate MarkCommand

MarkCommand -> Model : getFilteredPersonList()
activate Model

Model -> MarkCommand : lastShownList
deactivate Model

MarkCommand -> MarkCommand : createMarkedPerson(personToMark, newParticipationScores)
activate MarkCommand
MarkCommand -> MarkCommand : updatedPerson
deactivate MarkCommand

MarkCommand -> Model : setPerson(personToMark, updatedPerson)
activate Model

Model -> MarkCommand
deactivate Model

MarkCommand -> Model : updatedFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model

Model -> MarkCommand
deactivate Model

@enduml
