@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

mainframe: **sd** Mark person at specified week

participant "mc:MarkCommand" as MarkCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR

activate MarkCommand

create CommandResult
MarkCommand -> CommandResult : CommandResult(MESSAGE_MARK_PERSON_SUCCESS)
activate CommandResult

CommandResult -> MarkCommand : r
deactivate CommandResult

@enduml
